# Service pour exposer le themeparkride-service en interne au cluster
apiVersion: v1
kind: Service
metadata:
  name: themeparkride-service
  namespace: dev
spec:
  selector:
    app: themeparkride-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
